### ISSUE TITLE
Feature Request: Provide binary files for more operating systems and versions.

### ISSUE THREAD

**Issue by moonD4rk** [cvilsmeier/sqinn#3]
Hello, this is a fantastic project and I plan to use it in all my future projects. 

May I ask if it's possible to provide binary files for other operating system versions in the release? This can make it more convenient for more people to use.

It could be built and released using Github actions. For example, we may need:
- Windows 32/64 bit
- macOS 32/64 bit
- Linux 32/64 bit

**Comment by cvilsmeier** [comment]
Yes, I like the idea. Can you provide PR?

**Comment by moonD4rk** [comment]
> Yes, I like the idea. Can you provide PR?

Of course, I can! However, I am not very familiar with C as well as cross-platform compilation and building. It will take some time for me to study it, but I will submit a PR as soon as possible.

**Comment by cvilsmeier** [comment]
Merged your PR#4 but reverted it because i368 did build x64 binaries. And I do not have macos, so it's not possible for me to validate these binaries.
